"""Curation policy is shared, actor-parameterized, and importable without the Codex runner."""
from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import pytest
import yaml

from aiwiki.runtime import audit, curate, policy

MAINTAINER = "process:ai-wiki-maintainer"


def _concept(*, generated_by: str, generated_at: str = "2026-08-13T00:00:00Z", body: str = "X") -> str:
    fm = {
        "type": "Feature", "title": "X", "description": "x", "tags": ["x"], "status": "draft",
        "generated": {"by": generated_by, "at": generated_at},
        "sources": [{"id": "s", "resource": "/sources/s.md.source"}],
    }
    return "---\n" + yaml.safe_dump(fm, sort_keys=False) + f"---\n# Summary\n\n{body}\n"


@pytest.fixture
def bundle(tmp_path: Path) -> Path:
    (tmp_path / "features").mkdir()
    (tmp_path / "sources").mkdir()
    (tmp_path / "sources" / "s.md.source").write_text("evidence", encoding="utf-8")
    return tmp_path


def test_policy_imports_without_the_codex_runner() -> None:
    script = (
        "import sys, aiwiki.runtime.policy; "
        "loaded = sorted(m for m in ('aiwiki.runtime.curate', 'aiwiki.runtime.config') if m in sys.modules); "
        "print(loaded)"
    )
    result = subprocess.run(
        [sys.executable, "-c", script],
        env={**os.environ, "PYTHONPATH": str(Path(__file__).parents[1] / "src")},
        text=True, capture_output=True, timeout=30, check=True,
    )
    assert result.stdout.strip() == "[]"


def test_curate_and_audit_use_the_single_policy_copy() -> None:
    for name in (
        "CURATOR_ACTOR", "_agent_scope_errors", "_agent_symlink_snapshot", "_agent_tree_snapshot",
        "_concept_snapshot", "_curation_policy_errors", "_curation_provenance_errors",
        "_instant", "_isolated_agent_bundle", "_source_policy_errors", "_source_snapshot",
    ):
        assert getattr(curate, name) is getattr(policy, name), name
    assert audit.policy is policy
    assert policy.CURATOR_ACTOR == "process:ai-wiki-curator"


def test_new_concept_must_carry_the_given_actor(bundle: Path) -> None:
    before = policy._concept_snapshot(bundle)
    concept = bundle / "features" / "x.md"
    concept.write_text(_concept(generated_by=MAINTAINER), encoding="utf-8")

    assert policy._curation_policy_errors(bundle, before, actor=MAINTAINER) == []
    # The default actor is still the Codex curator, so existing callers are unchanged.
    assert policy._curation_policy_errors(bundle, before) == [
        "features/x.md: new concepts must set generated.by to 'process:ai-wiki-curator'",
    ]

    concept.write_text(_concept(generated_by=policy.CURATOR_ACTOR), encoding="utf-8")
    assert policy._curation_policy_errors(bundle, before, actor=MAINTAINER) == [
        f"features/x.md: new concepts must set generated.by to {MAINTAINER!r}",
    ]


def test_substantive_edit_of_legacy_concept_is_stamped_by_the_given_actor(bundle: Path) -> None:
    concept = bundle / "features" / "x.md"
    concept.write_text(_concept(generated_by=policy.CURATOR_ACTOR), encoding="utf-8")
    before = policy._concept_snapshot(bundle)

    # A concept first generated by the legacy curator id may be re-generated by the new actor.
    concept.write_text(
        _concept(generated_by=MAINTAINER, generated_at="2026-08-13T00:01:00Z", body="changed"),
        encoding="utf-8",
    )
    assert policy._curation_policy_errors(bundle, before, actor=MAINTAINER) == []

    # Keeping the old writer on a changed generation is rejected for the new actor.
    concept.write_text(
        _concept(generated_by=policy.CURATOR_ACTOR, generated_at="2026-08-13T00:01:00Z", body="changed"),
        encoding="utf-8",
    )
    assert policy._curation_policy_errors(bundle, before, actor=MAINTAINER) == [
        f"features/x.md: changed generation must set generated.by to {MAINTAINER!r}",
        f"features/x.md: substantive curation must set generated.by to {MAINTAINER!r}",
    ]


def test_generation_only_edit_reports_the_given_actor(bundle: Path) -> None:
    concept = bundle / "features" / "x.md"
    concept.write_text(_concept(generated_by=MAINTAINER), encoding="utf-8")
    before = policy._concept_snapshot(bundle)
    concept.write_text(_concept(generated_by="human:ceo"), encoding="utf-8")

    assert policy._curation_policy_errors(bundle, before, actor=MAINTAINER) == [
        "features/x.md: curation must not change generated metadata without substantive changes",
        f"features/x.md: changed generation must set generated.by to {MAINTAINER!r}",
    ]
